#!/bin/bash

# Selected text translator by ibrahim mohammad
# Email: ibrahim.mohammad.2015@gmail.com
# GitHub repository: https://github.com/IbrahimMohammad/shell_script
# No Rights Reserved

if [ $EUID -ne 0 ]; then # if non root user run the script
    echo 'This script must be run as root. use command sudo ./st-translator or su -c ./st-translator to run it.'
    echo 'يجب تشغيل هذا السكربت كمستخدم جذر. استخدم الأمر sudo ./st-translator أو su -c ./st-translator لتشغيله.'
    exit 1
fi
# install depends
apt-get --assume-yes install libnotify-bin xsel xbindkeys || exit 1
# run next commands as the logged in user
if [ -n "$SUDO_USER" ]; then
    user=$SUDO_USER
else
    user=$USERNAME
fi
# download .st-translator
su - $user --command 'wget -qO ~/.st-translator \
"https://raw.githubusercontent.com/IbrahimMohammad/shell_script/master/st-translator/.st-translator"'
# add script to shortcut alt+t
su - $user --command 'echo "\"~/.st-translator\"" >> ~/.xbindkeysrc'
su - $user --command 'echo "Alt + t" >> ~/.xbindkeysrc'
su - $user --command 'chmod 755 .st-translator'
# update xbindkeys to use the new shortcutkey
su - $user --command 'xbindkeys'
exit
