#!/bin/bash

# ayat installer.

# install aptitude
apt-get -y install aptitude
# activate i368 support
dpkg --add-architecture i386 && aptitude update
# install adobe air depends
aptitude -y install libxt6:i386 libnspr4-0d:i386 libgtk2.0-0:i386 libstdc++6:i386 libnss3-1d:i386 lib32nss-mdns libxml2:i386 libxslt1.1:i386 libcanberra-gtk-module:i386 gtk2-engines-murrine:i386 libgnome-keyring0:i386
# symblic links for adobe air
ln -s /usr/lib/i386-linux-gnu/libgnome-keyring.so.0 /usr/lib/libgnome-keyring.so.0
ln -s /usr/lib/i386-linux-gnu/libgnome-keyring.so.0.2.0 /usr/lib/libgnome-keyring.so.0.2.0
# download adobe air
wget http://airdownload.adobe.com/air/lin/download/2.6/AdobeAIRInstaller.bin
# install adobe air
chmod 755 AdobeAIRInstaller.bin
./AdobeAIRInstaller.bin && rm /usr/lib/libgnome-keyring.so.0 /usr/lib/libgnome-keyring.so.0.2.0
# install ayat
aptitude -y install libcurl3:i386
/opt/Adobe\ AIR/Versions/1.0/Adobe\ AIR\ Application\ Installer
