#!/bin/bash

# Ayat installer script by ibrahim mohammad
# Email: ibrahim.mohammad.2015@gmail.com
# GitHub repository: https://github.com/IbrahimMohammad/shell_script
# No Rights Reserved

if [ $EUID -ne 0 ]; then # if non root user run the script
	echo 'This script must be run as root. use command sudo ./ayat_installer or su -c ./ayat_installer to run it.'
	echo 'يجب تشغيل هذا السكربت كمستخدم جذر. استخدم الأمر sudo ./ayat_installer أو su -c ./ayat_installer لتشغيله.'
	exit 1
fi

get_file () {
	DOWNLOAD_FILE="wget --output-document=$1 $2$1"
	if [ ! -e $1 ]; then # if file doesn't exist, then download it
		$DOWNLOAD_FILE
	else # if file exist, then check it's md5sum
		if [ "$(md5sum $1)" != "$3  $1" ]; then # if it have different md5sum, then download it
			$DOWNLOAD_FILE
		fi
	fi
}

multi_arch_steps () { # commands needed for x64-bit and x32-bit systems
	# symbolic links to make adobe air able to see gnome-keyring
	ln -s /usr/lib/i386-linux-gnu/libgnome-keyring.so.0 /usr/lib/libgnome-keyring.so.0
	ln -s /usr/lib/i386-linux-gnu/libgnome-keyring.so.0.2.0 /usr/lib/libgnome-keyring.so.0.2.0
	# get adobe air
	get_file AdobeAIRInstaller.bin http://airdownload.adobe.com/air/lin/download/2.6/ a91369be7ab40e3c5d5bc9fb02b95041
	# install adobe air
	chmod 755 AdobeAIRInstaller.bin
	./AdobeAIRInstaller.bin -silent || exit 1
	# we don't need symbolic links any more
	rm /usr/lib/libgnome-keyring.so.0 /usr/lib/libgnome-keyring.so.0.2.0
	# get ayat
	get_file Ayat-v1.4.air https://dl.dropboxusercontent.com/s/js4efj0l4belci9/ 1cb481cab75b89256fce87b0279c6fbe
	# install ayat
	/opt/Adobe\ AIR/Versions/1.0/Adobe\ AIR\ Application\ Installer -silent $(pwd)/Ayat-v1.4.air
	# run ayat as the logged in user
	if [ -n "$SUDO_USER" ]; then
		user=$SUDO_USER
	else
		user=$USERNAME
	fi
	su - $user --command "/opt/Ayat/bin/Ayat &>> /dev/null&"
	exit
}

# here we go!
sys_arch="$(dpkg --print-architecture)"
# for 64-bit systems
if [ $sys_arch == "amd64" ]; then
	# activate i368 support
	dpkg --add-architecture i386
	# update package list
	apt-get update
	# install adobe air depends
	apt-get --assume-yes install libxt6:i386 libnspr4:i386 \
			libgtk2.0-0:i386 libstdc++6:i386 libnss3:i386 libnss-mdns:i386 libxml2:i386 libxslt1.1:i386 \
			libcanberra-gtk-module:i386 gtk2-engines-murrine:i386 libgnome-keyring0:i386 || exit 1
	# install libcurl for ayat sound
	apt-get --assume-yes install libcurl3:i386
	multi_arch_steps
# for 32-bit systems
elif [ $sys_arch == "i386" ]; then
	apt-get --assume-yes install libgnome-keyring0 || exit 1
	multi_arch_steps
# for other architectures
else
	echo "Sorry, this script is for 64-bit or 32-bit system."
	echo ".عذراً، هذا السكربت لنظام 64 بت أو 32 بت."
	exit
fi
